language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos-dev python-numpy
  - pip install -r requirements-dev.txt

install:
  - pip install -e .

script: "py.test tests"  